name: Preprocessing and Modeling CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies for preprocessing
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run preprocessing script
      run: |
        cd preprocessing
        python automate_Haldies.py

    - name: Upload preprocessed data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-data
        path: |
          preprocessing/titanic_preprocessed_train.csv
          preprocessing/titanic_preprocessed_test.csv
